title: Dorian Thornton
email: dorian.wolf@gmail.com
description: Dorian Thornton is a Product Designer and Developer at Ample Organics
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dorianthornton.com" 
facebook_link: https://www.facebook.com/dorian.wolf.thornton
instagram_link: https://www.instagram.com/dorian.wolf
github_link:  https://www.github.com/dorianwolf
linkedin_link:  https://www.linkedin.com/in/dorian-thornton/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
